# Dependabot configuration for automatic dependency updates and security fixes
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Yemen"
    open-pull-requests-limit: 10
    reviewers:
      - "EngDawood"
    assignees:
      - "EngDawood"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    # Group related updates together
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "aiohttp*"
          - "tortoise*"
          - "telethon*"
      major-updates:
        update-types:
          - "major"
    # Auto-merge security patches and minor updates
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"
      - dependency-type: "direct"
        update-type: "version-update:semver-patch"
    ignore:
      # Ignore specific packages that might cause issues
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Yemen"
    open-pull-requests-limit: 5
    reviewers:
      - "EngDawood"
    assignees:
      - "EngDawood"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "actions/*"
          - "docker/*"
          - "github/*"

  # Docker dependencies (if you have Dockerfile)
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "Asia/Yemen"
    open-pull-requests-limit: 3
    reviewers:
      - "EngDawood"
    assignees:
      - "EngDawood"
    commit-message:
      prefix: "docker"
      include: "scope"
