name: Publish to Test PyPI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.sample'
  workflow_dispatch: ~
jobs:
  build-n-publish:
    name: Build and publish package to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Build package
        run: |
          VERSION=$(git describe --tags --always --dirty)
          sed -E \
            -e "s#^v##" \
            -e "s#-#.dev#g" \
            -e "s#^#\__version__ = \"#" \
            -e "s#\[#\"#" \
            <<<"$VERSION" > src/version.py
          uv build --sdist --wheel --out-dir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          print_hash: true
          skip_existing: true
