name: Publish to PyPI
on:
  push:
    tags:
      - '**'
  workflow_dispatch: ~
jobs:
  build-n-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Build package
        run: |
          uv build --sdist --wheel --out-dir dist/
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags') && vars.PYPI_PUBLISH_ENABLED == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          print_hash: true
          skip_existing: true
